### ISSUE TITLE
Invalid JSON input

### ISSUE THREAD

**Issue by mahan21** [reportportal/agent-python-nosetests#15]
Every test case is failing when it's sending the tests results to reportportal. Seems like the receiver expects a START_TOKEN that is left out (see stack trace below).

```
ERROR: test_login_user_n3 (test_ut_api.TestLoginUser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/proj/backend-auth/venv/lib/python3.8/site-packages/nose/case.py", line 134, in run
    self.runTest(result)
  File "/home/user/proj/backend-auth/venv/lib/python3.8/site-packages/nose/case.py", line 152, in runTest
    test(result)
  File "/usr/lib/python3.8/unittest/case.py", line 736, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.8/unittest/case.py", line 649, in run
    result.startTest(self)
  File "/home/user/proj/backend-auth/venv/lib/python3.8/site-packages/nose/proxy.py", line 169, in startTest
    self.plugins.startTest(self.test)
  File "/home/user/proj/backend-auth/venv/lib/python3.8/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/home/user/proj/backend-auth/venv/lib/python3.8/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/home/user/proj/backend-auth/venv/lib/python3.8/site-packages/nose_reportportal/plugin.py", line 251, in startTest
    test.test_item = self.service.start_nose_item(self, test)
  File "/home/user/proj/backend-auth/venv/lib/python3.8/site-packages/nose_reportportal/service.py", line 119, in start_nose_item
    return self.rp.start_test_item(**start_rq)
  File "/home/user/proj/backend-auth/venv/lib/python3.8/site-packages/reportportal_client/service.py", line 286, in start_test_item
    item_id = _get_id(r)
  File "/home/user/proj/backend-auth/venv/lib/python3.8/site-packages/reportportal_client/service.py", line 66, in _get_id
    return _get_data(response)["id"]
  File "/home/user/proj/backend-auth/venv/lib/python3.8/site-packages/reportportal_client/service.py", line 98, in _get_data
    raise ResponseError(error_messages[0])
reportportal_client.errors.ResponseError: 4001: Incorrect Request. Invalid JSON input: Cannot deserialize instance of `java.util.ArrayList<com.epam.ta.reportportal.ws.model.ParameterResource>` out of START_OBJECT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList<com.epam.ta.reportportal.ws.model.ParameterResource>` out of START_OBJECT token
 at [Source: (PushbackInputStream); line: 1, column: 215] (through reference chain: com.epam.ta.reportportal.ws.model.StartTestItemRQ["parameters"])
```

**Comment by orzen** [comment]
This patch solve the issue:
https://github.com/reportportal/agent-python-nosetests/pull/16
