### ISSUE TITLE
`incorrect request error` raised once I run a simple test case

### ISSUE THREAD

**Issue by 0xIslamTaha** [reportportal/agent-python-nosetests#17]
**Test case code**
```python3
from unittest import TestCase
from selenium import webdriver


class BaseTest(TestCase):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def test001(self):
        driver = webdriver.Chrome()
        driver.get('http://google.com')
        self.assertIn('google', driver.current_url)
```

**ConfigFile**
```bash
[base]
rp_uuid = f871e6cb-e727-4fe4-ae6e-700a05ab9622
rp_endpoint =  http://ip172-18-0-18-bsnc12joudsg00def240-8080.direct.labs.play-with-docker.com
rp_project = superadmin_personal
rp_launch = superadmin_TEST_EXAMPLE
rp_launch_tags = Nose;Smoke
rp_launch_description = Smoke test
```

**Structure**
```bash
╰─➤  tree
.
├── rp.ini
└── test.py


```

**Execution results**
```bash
╭─islamtaha@RLYLTPZ175 /opt/code/github/test  
╰─➤  nosetests -vs --with-reportportal --rp-config-file rp.ini test.py                                                           1 ↵
ERROR

======================================================================
ERROR: test001 (test.BaseTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/islamtaha/.local/lib/python3.6/site-packages/nose/case.py", line 134, in run
    self.runTest(result)
  File "/home/islamtaha/.local/lib/python3.6/site-packages/nose/case.py", line 152, in runTest
    test(result)
  File "/usr/lib/python3.6/unittest/case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.6/unittest/case.py", line 578, in run
    result.startTest(self)
  File "/home/islamtaha/.local/lib/python3.6/site-packages/nose/proxy.py", line 169, in startTest
    self.plugins.startTest(self.test)
  File "/home/islamtaha/.local/lib/python3.6/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/home/islamtaha/.local/lib/python3.6/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/home/islamtaha/.local/lib/python3.6/site-packages/nose_reportportal/plugin.py", line 251, in startTest
    test.test_item = self.service.start_nose_item(self, test)
  File "/home/islamtaha/.local/lib/python3.6/site-packages/nose_reportportal/service.py", line 119, in start_nose_item
    return self.rp.start_test_item(**start_rq)
  File "/home/islamtaha/.local/lib/python3.6/site-packages/reportportal_client/service.py", line 300, in start_test_item
    item_id = _get_id(r)
  File "/home/islamtaha/.local/lib/python3.6/site-packages/reportportal_client/service.py", line 68, in _get_id
    return _get_data(response)["id"]
  File "/home/islamtaha/.local/lib/python3.6/site-packages/reportportal_client/service.py", line 100, in _get_data
    raise ResponseError(error_messages[0])
reportportal_client.errors.ResponseError: 4001: Incorrect Request. Invalid JSON input: Cannot deserialize instance of `java.util.ArrayList<com.epam.ta.reportportal.ws.model.ParameterResource>` out of START_OBJECT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList<com.epam.ta.reportportal.ws.model.ParameterResource>` out of START_OBJECT token
 at [Source: (PushbackInputStream); line: 1, column: 192] (through reference chain: com.epam.ta.reportportal.ws.model.StartTestItemRQ["parameters"])

----------------------------------------------------------------------
Ran 0 tests in 0.499s

FAILED (errors=1)
╰─➤  nosetests --with-reportportal --rp-config-file rp.ini test.py                                                               1 ↵
E
======================================================================
ERROR: test001 (test.BaseTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/islamtaha/.local/lib/python3.6/site-packages/nose/case.py", line 134, in run
    self.runTest(result)
  File "/home/islamtaha/.local/lib/python3.6/site-packages/nose/case.py", line 152, in runTest
    test(result)
  File "/usr/lib/python3.6/unittest/case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.6/unittest/case.py", line 578, in run
    result.startTest(self)
  File "/home/islamtaha/.local/lib/python3.6/site-packages/nose/proxy.py", line 169, in startTest
    self.plugins.startTest(self.test)
  File "/home/islamtaha/.local/lib/python3.6/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/home/islamtaha/.local/lib/python3.6/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/home/islamtaha/.local/lib/python3.6/site-packages/nose_reportportal/plugin.py", line 251, in startTest
    test.test_item = self.service.start_nose_item(self, test)
  File "/home/islamtaha/.local/lib/python3.6/site-packages/nose_reportportal/service.py", line 119, in start_nose_item
    return self.rp.start_test_item(**start_rq)
  File "/home/islamtaha/.local/lib/python3.6/site-packages/reportportal_client/service.py", line 300, in start_test_item
    item_id = _get_id(r)
  File "/home/islamtaha/.local/lib/python3.6/site-packages/reportportal_client/service.py", line 68, in _get_id
    return _get_data(response)["id"]
  File "/home/islamtaha/.local/lib/python3.6/site-packages/reportportal_client/service.py", line 100, in _get_data
    raise ResponseError(error_messages[0])
reportportal_client.errors.ResponseError: 4001: Incorrect Request. Invalid JSON input: Cannot deserialize instance of `java.util.ArrayList<com.epam.ta.reportportal.ws.model.ParameterResource>` out of START_OBJECT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList<com.epam.ta.reportportal.ws.model.ParameterResource>` out of START_OBJECT token
 at [Source: (PushbackInputStream); line: 1, column: 192] (through reference chain: com.epam.ta.reportportal.ws.model.StartTestItemRQ["parameters"])

----------------------------------------------------------------------
Ran 0 tests in 0.386s

FAILED (errors=1)
                                 
```

**Report AI**
![image](https://user-images.githubusercontent.com/17981089/89714973-a090e080-d9a2-11ea-9fee-9dedfb73405a.png)

**Comment by 0xIslamTaha** [comment]
I managed to fix it by installing the plugin from this repo, maybe the official released package needs to be updated
